export const BASE_URL = "http://127.0.0.1:8000/"
export const API_URL = "api/"
export const LOGIN_URL = API_URL + "token/"
export const TOKEN_REFRESH_URL = API_URL + "token/refresh/"
export const TOKEN_VERIFY_URL = API_URL + "token/verify/"
export const REGISTER_URL = API_URL + "auth/reg/"
export const EMAIL_VERIFY_URL = API_URL + "verify-email/"

export const REDIRECT_IF_LOGGED_IN_URL = "/workspace/"
export const REDIRECT_ON_LOGOUT_URL = "/login/"
export const REDIRECT_ON_REGISTER_URL = "/register-confirm/"